### PR TITLE
Replace route Closures with controller methods

### LINKED ISSUE #3: Can not be used with php artisan route:cache
just that, so is not suitable for production
```
LogicException  : Unable to prepare route [nova-vendor/cache-card/flush] for serialization. Uses Closure.
```

### PR DESCRIPTION
**Pull request by AegirLeet**
Fixes #3.

Also removes the duplicate `license` from composer.json.

### CODE REVIEW

**Comment by doriandigital** [comment]
When is this going to be merged with the master repository so people like me what use it already in production?

**Comment by leMaur** [comment]
Hey @dannyvink,
when do you schedule to merge this PR? 😉

**Comment by dannyvink** [comment]
Hey y'all, sorry I didn't see this. Let me look it over and I'll get the changes merged in.

**Comment by dannyvink** [comment]
Merged #5 which resolves this and cleans up a few things.

**Pull request closed without merging**
