### PR TITLE
Call to undefined method Vink\CacheCard\CacheCard::boot() fixed

### PR DESCRIPTION
**Pull request by JapSeyz**

### CODE REVIEW

**Comment by JapSeyz** [comment]
@dannyvink Hey, could you have a look at this, as the package is unusable without it.

**Comment by dannyvink** [comment]
Hmmmm... this should already be happening in the CardServiceProvider. To verify, you are loading this in 'cards' and not 'tools' in your 'NovaServiceProvider', correct?

**Comment by dannyvink** [comment]
Yep, just double checked the docs. A tool loads their resources from the Tool file, but a card loads it from the service provider. Make sure you are loading this from the cards array and not the tools array.

**Comment by JapSeyz** [comment]
I pasted the code from laravelnovatools.com, which results in this error, so that may also be the wrong file it's trying to load

**Comment by dannyvink** [comment]
The instructions there reference putting it into the cards array as well. Did you manage to get it working?

**Comment by JapSeyz** [comment]
Ah, I may have put it in the wrong array. I'll check when I'm at a pc

**Comment by JapSeyz** [comment]
Yeah, totally my fault, I added it to the tools array, not the cards..

**Pull request closed without merging**
